title: SpeechSafe
logo:
description: >- # this means to ignore newlines until "baseurl:"
  SpeechSafe, un sistema intelligente per la protezione uditiva e la comunicazione in ambienti di lavoro rumorosi.
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
# Build settings
#remote_theme: pages-themes/leap-day
#remote_theme: pages-themes/leap-day@v0.2.0